name: coverage
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/coverage.yaml'
      - 'R/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yaml'
      - 'R/**'
      - 'tests/**'
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-22.04
    name: coverage
    env:
      NOT_CRAN: TRUE
    steps:
      - uses: actions/checkout@v2
      - name: Setup r2u
        run: sudo bash scripts/ci/setup-r2u.sh
      - name: Install dependencies
        run: sudo bash scripts/ci/install-dependencies.sh
      - name: Session information
        run: sessionInfo()
        shell: Rscript {0}
      - name: Test coverage
        run: |
          library("covr")
          x <- package_coverage(quiet = FALSE, clean = FALSE)
          print(x)
          codecov(coverage = x)
        shell: Rscript {0}
